[package]
name = "progetto-pds-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
egui  = "0.29.1"
eframe = "0.29.1"
scrap = "0.5.0"
bincode = "1.3.3" # Per serializzare i dati
flate2 = "1.0.35" # Per comprimere i dati
sdl2 = "0.37.0"  # Binding Rust per SDL2